### ISSUE TITLE
Conversion of rotational speeds is not correct

### ISSUE THREAD

**Issue by Aym-brz** [sharkdp/numbat#427] opened 2024-05-14 11:01 UTC
When converting rotational speeds, the result is not correct
>>> 1 rpm -> rad/s

  1 rpm ➞ radian / second

    = 0.0166667 rad/s    [Activity or Frequency]

>>> 1 rad/s -> rpm

  1 radian / second ➞ rpm

    = 60 RPM    [Activity or Frequency]

**Comment by eminence** [comment] 2024-05-14 16:21
Duplicate of https://github.com/sharkdp/numbat/issues/373

**Closed** 2024-05-14 17:35 UTC
Labels: question
