### ISSUE TITLE
Windows 64bit release missing from v1.9.0

### ISSUE THREAD

**Issue by tech189** [sharkdp/numbat#290] opened 2024-01-03 09:52 UTC
The releases page for v1.9.0 only has a binary for the i686 architecture but not for x86_64 as before (https://github.com/sharkdp/numbat/releases/download/v1.8.0/numbat-v1.8.0-x86_64-pc-windows-msvc.zip)

**Comment by sharkdp** [comment] 2024-01-17 07:33
Thank you for reporting this.

I disabled the Windows build in question here in this commit: https://github.com/sharkdp/numbat/commit/4e9991cbfb25303a288ddc86fc363fe4c89d2d3a

As stated in the comment, the reason for this is a unit test failure that [occurred sporadically on this architecture (in CI)](https://github.com/sharkdp/numbat/actions/runs/7260809974/job/19780726294). I do not have access to a Windows machine myself, so I couldn't debug this.

@tech189 Would you perhaps be willing to look into this further? You'd have to install Rust (https://rustup.rs/), clone this repository and run `cargo test` on your machine (multiple times) in order to see if you can reproduce the error.

**Comment by tech189** [comment] 2024-01-18 00:00
I ran the tests a few times but I couldn't reproduce the error! Otherwise, the 32bit binary works okay for me.

**Comment by sharkdp** [comment] 2024-01-27 22:02
closed via #298

**Closed by sharkdp** 2024-01-27 22:02 UTC
