### ISSUE TITLE
Suggest correct casing if the entered unit doesn't exist

### ISSUE THREAD

**Issue by 5225225** [sharkdp/numbat#414] opened 2024-04-22 15:05 UTC
As a first time user, figuring out what this calls its data types is unintuitive

```
>>> 1mb to bytes
error: while type checking
  ┌─ <input:17>:1:2
  │
1 │ 1mb to bytes
  │  ^^ unknown identifier
```

same with `1kb` and `1KB`, both unrecognised. I *eventually* figured out that the correct units are `1MB` (1mB is millibyte, 1Mb is an error) and `1kB` (1KB is an error, as is 1Kb).

I think if you enter 1mb the most useful thing to do is either to just correct it for you and tell you it did that, or at the very least, tell me what i probably meant. Just showing an error is... unhelpful. I don't know if this applies to other units too, the data units are just the only ones I've spotted so far.

**Comment by eminence** [comment] 2024-04-22 15:18
Normally there are suggestions for these type of error.  For example:

```
>>> 1 niles
error: while type checking
  ┌─ <input:219>:1:3
  │
1 │ 1 niles
  │   ^^^^^ unknown identifier
  │
  = Did you mean 'miles'?
```

But the suggestion code is skipped for short identifiers (I think because there are so many 1 and 2 letter identifiers that standard edit-distance metrics don't work well here).

However in this case, I think we can do something like check to see if there's an identifier that only differs in case and make suggestions based on that

**Comment by sharkdp** [comment] 2024-04-22 17:21
Thank you for the feedback. Duplicate of https://github.com/sharkdp/numbat/issues/103?

**Comment by sharkdp** [comment] 2024-04-22 17:22
> But the suggestion code is skipped for short identifiers (I think because there are so many 1 and 2 letter identifiers that standard edit-distance metrics don't work well here).
> 
> However in this case, I think we can do something like check to see if there's an identifier that only differs in case and make suggestions based on that

:+1:

**Closed** 2024-04-24 11:22 UTC
